### ISSUE TITLE
Hide home page on loading

### ISSUE THREAD

**Issue by reharri7** [reharri7/cdshort#3]

**Comment by Yasir761** [comment]
Can you please elaborate on this issue, much appreciated, and wanted to work on this issue.

**Comment by B1910668-TN** [comment]
Hi,  you want to have the line "loading" before the homepage appears, right? If that's the case, I've helped you get it done. I will push it to the dev branch, you can check it out. Hope it can help you.

**Comment by reharri7** [comment]
This issue will require re-implementing OnInit on the home.page.ts file. 

1.  Create a boolean class variable named isLoading and set it to false initially. 
2. In the ngOnInit method (a lifecycle hook provided by Angular) set isLoading to true. 
3. Implement all the redirect functionality that is provided in the constructor. 
4. At then end of the ngOnInit method, set isLoading to false. In the home.page.html file, use the ngIf directive to conditionally show the content of that page whether the page is loading or not. 
5. If it is loading, show an `<ion-spinner />`

Please create a feature branch for this and make a pull request to dev
