### ISSUE TITLE
Member-card-component

### ISSUE THREAD

**Issue by reharri7** [reharri7/cdshort#6]
Placeholder for member card component that will live on the directory page

**Comment by CMVaughn** [comment]
I'm assuming we are going to be using the ionic-card available with the ionic framework. Is there a particular theme we are aiming for? What information are we wanting to display?

**Comment by reharri7** [comment]
@CMVaughn I think we are going to ditch this

**Comment by reharri7** [comment]
Closing this. Business needs changing to something similar to linktree page
